# Generated by Django 3.0.11 on 2021-01-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210119_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choise',
            name='choise_text',
        ),
        migrations.AddField(
            model_name='choise',
            name='choise_text1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choise',
            name='choise_text2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choise',
            name='choise_text3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choise',
            name='choise_text4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
